### PR TITLE
Support prepared statements

### PR DESCRIPTION
**Pull request by kerams**
Implements #34.

@melanore

### CODE REVIEW

**Comment by melanore** [comment]
Cool! Any chance changes in this PR could be covered by unit tests? There's some serious potential for regression, so it would be good to have this feature covered by tests before merge/release. You can find test project in `tests` folder of the repo.

@dmitry-a-morozov, could you have a look at PR please?

**Comment by kerams** [comment]
Any idea what this is?
```
fsharp.data.npgsql\tests\obj\Debug\netcoreapp2.1\Tests.AssemblyInfo.fs(10,48): error FS0039: The type 'UserSecrets' is not defined. [fsharp.data.npgsql\tests\Tests.fsproj]
```

**Comment by kerams** [comment]
Thanks. I'll take care of the XML docs, tests and the other PR tomorrow.

**Comment by melanore** [comment]
Thanks again for the PR. That's very helpful.

**Comment by kerams** [comment]
Ugh, the tests now build, but fail at runtime with `System.IO.FileNotFoundException : Could not load file or assembly 'FSharp.Core, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`

Looks like a missing assembly redirect? Does it work for you?

**Comment by melanore** [comment]
That's weird. Try to update Fsharp.Core package to 4.5.0 version in project

**Comment by kerams** [comment]
What kind of tests do you want to see here? Should I just duplicate a couple of other tests with Prepare set to true? Whether or not it did anything can be proved by checking the private state inside Npgsql. It's also possible to list prepared statements for the current session by sending a query to the DB, but I'm not sure we can rely on the 2 sharing the same session/physical connection.

**Comment by kerams** [comment]
This seems to work nicely.

```fsharp
[<Literal>]
let commandText = "select id from public.user limit 1"

use con = new Npgsql.NpgsqlConnection(connectionString)
con.Open()
con.UnprepareAll()

let cmd = new FSharp.Data.Npgsql.NpgsqlCommand<commandText, connectionString, Prepare = true>(con)
cmd.Execute() |> ignore

let connector = typeof<Npgsql.NpgsqlConnection>.GetField("Connector", BindingFlags.NonPublic ||| BindingFlags.Instance).GetValue(con)
let psManager = connector.GetType().GetField("PreparedStatementManager", BindingFlags.NonPublic ||| BindingFlags.Instance).GetValue(connector)
let preparedStatements = psManager.GetType().GetProperty("BySql", BindingFlags.NonPublic ||| BindingFlags.Instance).GetValue(psManager)
let wasPrepared = preparedStatements.GetType().GetMethod("ContainsKey", BindingFlags.Instance ||| BindingFlags.Public).Invoke(preparedStatements, [| commandText |]) :?> bool
```

**Comment by melanore** [comment]
Reflection based preparation check looks nice. If a bunch of such tests could be pushed - I think this PR is ready to be merged.

**Comment by kerams** [comment]
I'm trying to test the ability to override `Prepare` by doing
```fsharp
type DvdRental = NpgsqlConnection<connectionStringName, Config = config>
type DvdRentalPrepared = NpgsqlConnection<connectionStringName, Config = config, Prepare = true>

//...

[<Fact>]
let ``Command prepared by default when set on type``() =
    use conn = openConnection()
    conn.UnprepareAll()

    use cmd = DvdRentalPrepared.CreateCommand<getActorByName, XCtor = true>(conn)
    cmd.Execute("", "") |> ignore

    Assert.True(isStatementPrepared conn)
```

This test fails though. I have a suspicion that there is something funny going on with TP caching, because when I move the test to the very top of the file, it passes, but then this one fails:

```fsharp
[<Fact>]
let ``Command not prepared by default``() =
    use conn = openConnection()
    conn.UnprepareAll()

    use cmd = DvdRental.CreateCommand<getActorByName, XCtor = true>(conn)
    cmd.Execute("", "") |> ignore

    Assert.False(isStatementPrepared conn)
```
indicating that everything is prepared... I have no idea how to work around this. Should I just forget about the override test?

**Pull request merged**
