### PR TITLE
Error reading Postgis - Geometry column #93

### PR DESCRIPTION
**Pull request by sandeepc24**

### CODE REVIEW

**Comment by sandeepc24** [comment]
Could someone see why the tests are failing?

**Comment by daz10000** [comment]
Ugg sorry I looked into this a while back and made a little progress but couldn’t ultimately understand why it is failing in CI environment but was working locally. Then I got sucked into a bunch of local fires here.  I tried a few different docker configurations and could t work out what had changed to cause them to fail after working for a while.  Might be worth starting a new ticket on this and I can try to recall what I tried before getting distracted 

Von meinem iPhone gesendet

**Comment by sandeepc24** [comment]
@daz10000 would it be possible for you to test my changes locally on your computer? If they pass could you please publish new nuget as I am blocked because of this issue.

**Comment by sandeepc24** [comment]
@daz10000 I think it might be something to do with `global.json`, I 'll create a PR for it to see how it goes.

**Comment by daz10000** [comment]
On Thu, Jun 25, 2020 at 02:14:49AM -0700, Sandeep Chandra wrote:
> @daz10000 would it be possible for you to test my changes locally on your computer? If they pass could you please publish new nuget as I am blocked because of this issue.
> 

Sorry to hear that - can take a look next hour or so.

**Comment by daz10000** [comment]
Should be merged in 0.2.10-beta.   I haven't done a release on this project for a little while so let me know ASAP if I f&*ek anything up but should be good.

**Comment by sandeepc24** [comment]
Thanks @daz10000 , it is working fine.

**Pull request merged**
